package com.jhipster.smartdine.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DishAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishAllPropertiesEquals(Dish expected, Dish actual) {
        assertDishAutoGeneratedPropertiesEquals(expected, actual);
        assertDishAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishAllUpdatablePropertiesEquals(Dish expected, Dish actual) {
        assertDishUpdatableFieldsEquals(expected, actual);
        assertDishUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishAutoGeneratedPropertiesEquals(Dish expected, Dish actual) {
        assertThat(actual)
            .as("Verify Dish auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishUpdatableFieldsEquals(Dish expected, Dish actual) {
        assertThat(actual)
            .as("Verify Dish relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").isEqualTo(expected.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishUpdatableRelationshipsEquals(Dish expected, Dish actual) {
        assertThat(actual)
            .as("Verify Dish relationships")
            .satisfies(a -> assertThat(a.getIngridientName()).as("check ingridientName").isEqualTo(expected.getIngridientName()))
            .satisfies(a -> assertThat(a.getPurchases()).as("check purchases").isEqualTo(expected.getPurchases()));
    }
}
