package com.jhipster.smartdine.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuDishesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuDishesAllPropertiesEquals(MenuDishes expected, MenuDishes actual) {
        assertMenuDishesAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuDishesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuDishesAllUpdatablePropertiesEquals(MenuDishes expected, MenuDishes actual) {
        assertMenuDishesUpdatableFieldsEquals(expected, actual);
        assertMenuDishesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuDishesAutoGeneratedPropertiesEquals(MenuDishes expected, MenuDishes actual) {
        assertThat(actual)
            .as("Verify MenuDishes auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuDishesUpdatableFieldsEquals(MenuDishes expected, MenuDishes actual) {
        assertThat(actual)
            .as("Verify MenuDishes relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuDishesUpdatableRelationshipsEquals(MenuDishes expected, MenuDishes actual) {
        assertThat(actual)
            .as("Verify MenuDishes relationships")
            .satisfies(a -> assertThat(a.getDishNames()).as("check dishNames").isEqualTo(expected.getDishNames()));
    }
}
