package com.jhipster.smartdine.domain;

import static com.jhipster.smartdine.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseAllPropertiesEquals(Purchase expected, Purchase actual) {
        assertPurchaseAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseAllUpdatablePropertiesEquals(Purchase expected, Purchase actual) {
        assertPurchaseUpdatableFieldsEquals(expected, actual);
        assertPurchaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseAutoGeneratedPropertiesEquals(Purchase expected, Purchase actual) {
        assertThat(actual)
            .as("Verify Purchase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseUpdatableFieldsEquals(Purchase expected, Purchase actual) {
        assertThat(actual)
            .as("Verify Purchase relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a ->
                assertThat(a.getAmmount()).as("check ammount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPaymentMethod()).as("check paymentMethod").isEqualTo(expected.getPaymentMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseUpdatableRelationshipsEquals(Purchase expected, Purchase actual) {
        assertThat(actual)
            .as("Verify Purchase relationships")
            .satisfies(a -> assertThat(a.getDishes()).as("check dishes").isEqualTo(expected.getDishes()));
    }
}
